name: Gradle
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SetUp
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Permissions
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew --no-daemon build
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SetUp
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Permissions
      run: chmod +x gradlew
    - name: Test
      run: ./gradlew --no-daemon test
